version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore: # managed by intellij-updater
      - dependency-name: "com.jetbrains.rd:rd-gen"
      - dependency-name: "org.jetbrains.kotlin.jvm"
      - dependency-name: "org.jetbrains.kotlin:kotlin-stdlib"
